### ISSUE TITLE
Tutorial Picture to .xpm

### ISSUE THREAD

**Issue by Cerberus2290** [S-LucasSerrano/miniLibX_sample#1]
First of all, thank you very much for this very clear and comprehensive explanation. It is a joy to read and follow along.

My question is how can I create my own custom .xpm files for sprites, background, etc?

Could you add a tutorial for this as well?
Have I not read carefully enough and it's already here.

Thank you again for your hard work!

**Comment by S-LucasSerrano** [comment]
Hi Tom! Thank you for your comment, Im glad you found it useful.

Im not sure if I know what you mean. If you already have an image you want to use in your project, but it is in another file format, you can use an online converter like [this one here](https://anyconv.com/png-to-xpm-converter/). Thats the one I used but you can use any other one really. I got some of the images I use from [the Kenney’s website](https://kenney.nl/assets?q=2d). He is a cool guy that creates free assets for everyone to use in their games.
If you want to draw your own image, I used [Piskel](https://www.piskelapp.com/p/create/sprite) to create the image of the main character for my so_long project. Its a free online tool to draw pixel sprites. Its really easy to use and you can then download the image as a png and use the converter to turn it to an xpm. And if you know how to use Photoshop you can do it with it and, again, download the image as a png and convert it to an xpm. If you dont have Photoshop you can use this cool free online copy of it called [Photopea](https://www.photopea.com/). But it its basically Photoshop so you still need to know how to use it haha.

Hope this answers your question. Cheers!

**Comment by S-LucasSerrano** [comment]
Hi Tom! Thank you for your comment, Im glad you found it useful.

Im not sure if I know what you mean. If you already have an image you want to use in your project, but it is in another file format, you can use an online converter like [this one here](https://anyconv.com/png-to-xpm-converter/). Thats the one I used but you can use any other one really. I got some of the images I use from [the Kenney’s website](https://kenney.nl/assets?q=2d). He is a cool guy that creates free assets for everyone to use in their games.
If you want to draw your own image, I used [Piskel](https://www.piskelapp.com/p/create/sprite) to create the image of the main character for my so_long project. Its a free online tool to draw pixel sprites. Its really easy to use and you can then download the image as a png and use the converter to turn it to an xpm. And if you know how to use Photoshop you can do it with it and, again, download the image as a png and convert it to an xpm. If you dont have Photoshop you can use this cool free online copy of it called [Photopea](https://www.photopea.com/). But it its basically Photoshop so you still need to know how to use it haha.

Hope this answers your question. Cheers!

**Comment by Cerberus2290** [comment]
Thank you very much for the elaborate explanation.
Keep up the good work!
